# ---------- Build Stage ----------
FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /app

# Copy the entire multi-module project (so parent + shared-events + this service)
COPY . .

RUN mvn clean install -DskipTests

# Build this specific service and its dependencies
RUN mvn -pl orderProcessing -am clean package -DskipTests

# ---------- Run Stage ----------
FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=build /app/orderProcessing/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
